### PR TITLE
Add start script that kills previous instance of server and starts new instance

### PR DESCRIPTION
**Pull request by nayak16**
I know this script was deleted initially. However I found it easier, if you are changing server specific code, to use this script to restart the server and start another fresh instance in the background. Speeds up development. Let me know what you guys think.

### CODE REVIEW

**Comment by yrkumar** [comment]
2 things:
- the `source scripts/sourcelib` line is no longer necessary
- will that `grep` kill the first result that contains `server` in the list of processes, even if it isn't Tango?

**Comment by nayak16** [comment]
I'll remove that line. And yes actually it will. I'll make the regex more specific

**Comment by yrkumar** [comment]
@nayak16 should I close this PR or do you still want to merge this in?

**Comment by nayak16** [comment]
Close this PR. Script isn't necessary.

**Pull request closed without merging**
