### PR TITLE
Add a dockerfile allowing grading of Java and dotnet programs

### PR DESCRIPTION
**Pull request by cool00geek**
Add a dockerfile for Java (OpenJDK 11) and .NET (.NET 3.1) so Tango can grade assignments in both Java and .NET.

To build the Java image:
`docker build -t autograding_java -f Dockerfile_java .` from the vmms/ directory

To build the .NET image: `docker build -t autograding_dotnet -f Dockerfile_dotnet .` from the vmms/ directory

### CODE REVIEW

**Comment by fanpu** [comment]
Hi @cool00geek, thank you for your contribution! It looks really good at first glance and we will be taking a detailed look shortly.

**Comment by cool00geek** [comment]
Great thank you! Please let me know if there's anything else I should add or change before it can be merged.

**Comment by fanpu** [comment]
Do you have sample labs in Java and .NET that you would be willing to share in order to test the autograding images? In particular there has actually been some demand from the community for Java labs and autograders, so it would be really helpful as a reference for updating the documentation for Java labs. Thanks!

**Comment by cool00geek** [comment]
I don't know how to create a Tango job directly, but I have the sample autograde job I have been using to test it. I have attached `javatest` and `dotnettest` as well as `hello.java` and `hello.cs` to test the java and dotnet programs respectively. 

[tango_test.zip](https://github.com/autolab/Tango/files/5611165/tango_test.zip)

**Review by fanpu — APPROVED** [review]
Sorry about the delay, I got caught up for finals in the last few weeks. I've tested it and it's great, thanks so much as well for providing the sample autograders! We'll be updating the documentation on sample labs for autograding soon, and I'll make sure to credit you.

**Pull request merged**
