### PR TITLE
Make the JobManager thread a daemon

### PR DESCRIPTION
**Pull request by cg2v**
The JobManager threas was not set up as a daemon, so it was not possible
to shut down JobManager or non-redis tango-rest with SIGINT or SIGTERM

### CODE REVIEW

**Comment by cg2v** [comment]
Not quite right - the standalone JobManager now exits immediately

**Comment by cg2v** [comment]
And it's back to not exiting on Ctrl-C. maybe jobManager.py's main should just call signal.pause()

A more invasive possibility is to only use a thread when the JobManager is runnung inside TangoREST

**Comment by mihirpandya** [comment]
The way we normally terminate the job manager is to send it a SIGTSTP (ctrl-z) signal first and then to kill it:

* Ctrl-Z
* `kill %1`

**Comment by yrkumar** [comment]
Closed by b654c6e3fba59182b2a4cd7b4cb543a5bc727f0a

**Pull request closed without merging**
