### PR TITLE
Updated API for pool to return all pools if no pool name is given.

### PR DESCRIPTION
**Pull request by mihirpandya**
@ymzong You can test this with the dashboard.

### CODE REVIEW

**Comment by mihirpandya** [comment]
@yrkumar Can you update the command-line to not give a pool name by default?

**Comment by ymzong** [comment]
Thanks @mp, I'll test it in a bit and merge!

**Comment by mihirpandya** [comment]
that's not my github handle bruh...

**Comment by ymzong** [comment]
Okay, Mr. Pandya.

**Comment by ymzong** [comment]
:+1:

**Pull request merged**
