### PR TITLE
Added Travis test routine.

### PR DESCRIPTION
**Pull request by ymzong**
This PR is to notify Travis of my tests.

Do not merge yet!

### CODE REVIEW

**Comment by ymzong** [comment]
Update: currently tests fail to go through due to docker/docker#12177.

**Comment by mihirpandya** [comment]
Nice! Since docker has issues with Travis, you could try doing this with EC2. Lmk if you need help setting those things up.

**Comment by ymzong** [comment]
By travis-ci/travis-ci#1196 -- Travis only supports kernel version 2.8, which cannot run Docker, and also there's no ETA for bumping the kernel version. :disappointed:

**Comment by jez** [comment]
There are other CI services that do support it I think. I'm not sure how it would work, because Tango uses Docker somewhat differently than most projects. One CI service that I tend to see used often with Docker is [Circle CI](https://circleci.com/).

**Comment by ymzong** [comment]
`Circle.CI` looks great! I will give it a try!

**Comment by yrkumar** [comment]
@ymzong I'm going to close this PR since it's no longer relevant. feel free to open it up again if you feel like you want to discuss it further.

**Pull request closed without merging**
